/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.InformationController;
import database.transactions.AccountInformation;
import gui.settings.ActionSettings;
import gui.settings.ButtonSettings;
import gui.settings.IRegulyator;
import gui.settings.IconSettings;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JButton;

/**
 *
 * @author user
 */
public class AccountPage extends javax.swing.JFrame implements IRegulyator, InformationController{

    /**
     * Creates new form AccountPage
     */
    public AccountPage() {
        initComponents();
        getEdits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountPagePanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        nameSurnameLabel = new javax.swing.JLabel();
        euroIcon = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        withDrawMoneyIcon = new javax.swing.JLabel();
        withDrawMoneyLabel1 = new javax.swing.JButton();
        depositMoneyIcon = new javax.swing.JLabel();
        depositMoneyLabel2 = new javax.swing.JButton();
        transferİcon = new javax.swing.JLabel();
        transferButton = new javax.swing.JButton();
        paymentsIcon = new javax.swing.JLabel();
        paymentsButton = new javax.swing.JButton();
        settingsIcon = new javax.swing.JLabel();
        logoutIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        accountPagePanel.setBackground(new java.awt.Color(204, 204, 204));
        accountPagePanel.setForeground(new java.awt.Color(102, 102, 255));

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(102, 102, 255));
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("WELCOME");

        nameSurnameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nameSurnameLabel.setForeground(new java.awt.Color(102, 102, 255));
        nameSurnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameSurnameLabel.setText("[USER'S NAME SURNAME]");

        euroIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/euroIcon.png"))); // NOI18N

        balanceLabel.setFont(new java.awt.Font("Source Code Pro", 1, 40)); // NOI18N
        balanceLabel.setText("[BALANCE]");

        withDrawMoneyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/withdrawIcon.png"))); // NOI18N

        withDrawMoneyLabel1.setBackground(new java.awt.Color(204, 255, 255));
        withDrawMoneyLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        withDrawMoneyLabel1.setText("WithDraw Money");
        withDrawMoneyLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        withDrawMoneyLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                withDrawMoneyLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                withDrawMoneyLabel1MouseExited(evt);
            }
        });
        withDrawMoneyLabel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withDrawMoneyLabel1ActionPerformed(evt);
            }
        });

        depositMoneyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/safeİcon.png"))); // NOI18N

        depositMoneyLabel2.setBackground(new java.awt.Color(255, 102, 153));
        depositMoneyLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        depositMoneyLabel2.setText("Deposit Money");
        depositMoneyLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        depositMoneyLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                depositMoneyLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                depositMoneyLabel2MouseExited(evt);
            }
        });
        depositMoneyLabel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositMoneyLabel2ActionPerformed(evt);
            }
        });

        transferİcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/transferİcon1.png"))); // NOI18N

        transferButton.setBackground(new java.awt.Color(204, 204, 0));
        transferButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        transferButton.setText("Transfer");
        transferButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transferButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transferButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transferButtonMouseExited(evt);
            }
        });
        transferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferButtonActionPerformed(evt);
            }
        });

        paymentsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/paymentsIcon.png"))); // NOI18N

        paymentsButton.setBackground(new java.awt.Color(255, 204, 204));
        paymentsButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        paymentsButton.setText("Payments");
        paymentsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paymentsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paymentsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paymentsButtonMouseExited(evt);
            }
        });
        paymentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentsButtonActionPerformed(evt);
            }
        });

        settingsIcon.setBackground(new java.awt.Color(255, 255, 51));
        settingsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/settingsIcon.png"))); // NOI18N
        settingsIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settingsIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsIconMouseClicked(evt);
            }
        });

        logoutIcon.setBackground(new java.awt.Color(255, 255, 51));
        logoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/logoutIcon.png"))); // NOI18N
        logoutIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout accountPagePanelLayout = new javax.swing.GroupLayout(accountPagePanel);
        accountPagePanel.setLayout(accountPagePanelLayout);
        accountPagePanelLayout.setHorizontalGroup(
            accountPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPagePanelLayout.createSequentialGroup()
                .addGroup(accountPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountPagePanelLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(euroIcon)
                        .addGap(18, 18, 18)
                        .addComponent(balanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(accountPagePanelLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(nameSurnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountPagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountPagePanelLayout.createSequentialGroup()
                        .addGroup(accountPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(withDrawMoneyLabel1)
                            .addComponent(withDrawMoneyIcon))
                        .addGap(51, 51, 51)
                        .addGroup(accountPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(depositMoneyIcon)
                            .addComponent(depositMoneyLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(accountPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountPagePanelLayout.createSequentialGroup()
                                .addComponent(transferButton)
                                .addGap(64, 64, 64))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountPagePanelLayout.createSequentialGroup()
                                .addComponent(transferİcon)
                                .addGap(51, 51, 51)))
                        .addGroup(accountPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(paymentsIcon)
                            .addComponent(paymentsButton))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountPagePanelLayout.createSequentialGroup()
                        .addComponent(logoutIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186)
                        .addComponent(settingsIcon)
                        .addContainerGap())))
        );

        accountPagePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {transferButton, transferİcon, withDrawMoneyIcon, withDrawMoneyLabel1});

        accountPagePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {depositMoneyIcon, paymentsIcon});

        accountPagePanelLayout.setVerticalGroup(
            accountPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPagePanelLayout.createSequentialGroup()
                .addGroup(accountPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountPagePanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(accountPagePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(accountPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(settingsIcon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(logoutIcon))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameSurnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(accountPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balanceLabel)
                    .addComponent(euroIcon))
                .addGap(12, 12, 12)
                .addGroup(accountPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(accountPagePanelLayout.createSequentialGroup()
                        .addGroup(accountPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(accountPagePanelLayout.createSequentialGroup()
                                .addComponent(transferİcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(accountPagePanelLayout.createSequentialGroup()
                                .addComponent(paymentsIcon)
                                .addGap(14, 14, 14)))
                        .addGroup(accountPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(transferButton)
                            .addComponent(paymentsButton)))
                    .addGroup(accountPagePanelLayout.createSequentialGroup()
                        .addGroup(accountPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(accountPagePanelLayout.createSequentialGroup()
                                .addComponent(withDrawMoneyIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(accountPagePanelLayout.createSequentialGroup()
                                .addComponent(depositMoneyIcon)
                                .addGap(20, 20, 20)))
                        .addGroup(accountPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(withDrawMoneyLabel1)
                            .addComponent(depositMoneyLabel2))))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accountPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accountPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void withDrawMoneyLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withDrawMoneyLabel1MouseEntered
        this.setBgFg(evt.getComponent());
        IconSettings.changeIcon(withDrawMoneyIcon, "withdrawIcon2");
    }//GEN-LAST:event_withDrawMoneyLabel1MouseEntered

    private void withDrawMoneyLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withDrawMoneyLabel1MouseExited
        ButtonSettings.setOriginalBgFg((JButton) evt.getComponent());
        IconSettings.setOriginalIcon(withDrawMoneyIcon);
    }//GEN-LAST:event_withDrawMoneyLabel1MouseExited

    private void depositMoneyLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositMoneyLabel2MouseEntered
        this.setBgFg(evt.getComponent());
        IconSettings.changeIcon(depositMoneyIcon, "safeİcon2");
    }//GEN-LAST:event_depositMoneyLabel2MouseEntered

    private void depositMoneyLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositMoneyLabel2MouseExited
        ButtonSettings.setOriginalBgFg((JButton) evt.getComponent());
        IconSettings.setOriginalIcon(depositMoneyIcon);
    }//GEN-LAST:event_depositMoneyLabel2MouseExited

    private void transferButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferButtonMouseEntered
        this.setBgFg(evt.getComponent());
        IconSettings.changeIcon(transferİcon, "transferİcon2");
    }//GEN-LAST:event_transferButtonMouseEntered

    private void transferButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferButtonMouseExited
        ButtonSettings.setOriginalBgFg((JButton) evt.getComponent());
        IconSettings.setOriginalIcon(transferİcon);
    }//GEN-LAST:event_transferButtonMouseExited

    private void paymentsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentsButtonMouseEntered
        this.setBgFg(evt.getComponent());
        IconSettings.changeIcon(paymentsIcon, "paymentsIcon2");
    }//GEN-LAST:event_paymentsButtonMouseEntered

    private void paymentsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentsButtonMouseExited
        ButtonSettings.setOriginalBgFg((JButton) evt.getComponent());
        IconSettings.setOriginalIcon(paymentsIcon);
    }//GEN-LAST:event_paymentsButtonMouseExited

    private void withDrawMoneyLabel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withDrawMoneyLabel1ActionPerformed
        ActionSettings.setVisible(this, new WithDrawMoneyPage());
    }//GEN-LAST:event_withDrawMoneyLabel1ActionPerformed

    private void depositMoneyLabel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositMoneyLabel2ActionPerformed
        ActionSettings.setVisible(this, new DepositMoneyPage());
    }//GEN-LAST:event_depositMoneyLabel2ActionPerformed

    private void transferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferButtonActionPerformed
        ActionSettings.setVisible(this, new TransferPage());
    }//GEN-LAST:event_transferButtonActionPerformed

    private void paymentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentsButtonActionPerformed
        ActionSettings.setVisible(this, new PaymentsPage());
    }//GEN-LAST:event_paymentsButtonActionPerformed

    private void logoutIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutIconMouseClicked
        ActionSettings.setVisible(this, new LoginPage());
    }//GEN-LAST:event_logoutIconMouseClicked

    private void settingsIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsIconMouseClicked
        ActionSettings.setVisible(this, new SettingsPage());
    }//GEN-LAST:event_settingsIconMouseClicked

    private void setBgFg(Component c){
        ButtonSettings.setBgFg((JButton)c, Color.black, Color.white);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountPagePanel;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JLabel depositMoneyIcon;
    private javax.swing.JButton depositMoneyLabel2;
    private javax.swing.JLabel euroIcon;
    private javax.swing.JLabel logoutIcon;
    private javax.swing.JLabel nameSurnameLabel;
    private javax.swing.JButton paymentsButton;
    private javax.swing.JLabel paymentsIcon;
    private javax.swing.JLabel settingsIcon;
    private javax.swing.JButton transferButton;
    private javax.swing.JLabel transferİcon;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JLabel withDrawMoneyIcon;
    private javax.swing.JButton withDrawMoneyLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void getEdits() {
        this.setLocationRelativeTo(null);
        accountPagePanel.setFocusable(true);
        this.nameSurnameLabel.setText(getAccountInformation().getNameSurname());
        this.balanceLabel.setText(String.valueOf(getAccountInformation().getBalance()));
    }

    @Override
    public boolean validInformation() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public AccountInformation getAccountInformation() {
        return AccountInformation.getInstance();
    }
}
