/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.InformationController;
import database.transactions.AccountInformation;
import database.transactions.UserApply;
import gui.settings.ActionSettings;
import gui.settings.ButtonSettings;
import gui.settings.Dialogs;
import gui.settings.IRegulyator;
import gui.settings.TextSettings;
import java.awt.Color;
import java.awt.Dialog;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class ApplyPage extends javax.swing.JFrame implements IRegulyator, InformationController {

    private UserApply userApplyObject = null;

    /**
     * Creates new form ApplyPage
     */
    public ApplyPage() {
        initComponents();
        getEdits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adSoyadLabel2 = new javax.swing.JLabel();
        adSoyadText2 = new javax.swing.JTextField();
        applyPagePanel = new javax.swing.JPanel();
        adSoyadLabel = new javax.swing.JLabel();
        personalInformationlabel = new javax.swing.JLabel();
        adSoyadText = new javax.swing.JTextField();
        customerNoLabel = new javax.swing.JLabel();
        customerNoText = new javax.swing.JTextField();
        phoneNoLabel = new javax.swing.JLabel();
        phoneNoText = new javax.swing.JTextField();
        personalInformationlabel1 = new javax.swing.JLabel();
        securityQuestionLabel = new javax.swing.JLabel();
        securityQuestion = new javax.swing.JComboBox<>();
        securityAnswerLabel = new javax.swing.JLabel();
        securityAnswerText = new javax.swing.JTextField();
        applyButton = new javax.swing.JButton();
        previousIcon = new javax.swing.JLabel();

        adSoyadLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adSoyadLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        adSoyadLabel2.setText("Ad Soyad :");

        adSoyadText2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sweet Bank Apply Page");

        applyPagePanel.setBackground(new java.awt.Color(255, 255, 204));

        adSoyadLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adSoyadLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        adSoyadLabel.setText("Ad Soyad :");

        personalInformationlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        personalInformationlabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        personalInformationlabel.setText("Security Information");

        adSoyadText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adSoyadText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adSoyadTextActionPerformed(evt);
            }
        });

        customerNoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        customerNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        customerNoLabel.setText("Customer No : ");

        customerNoText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        phoneNoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phoneNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        phoneNoLabel.setText("Phone No :");

        phoneNoText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        personalInformationlabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        personalInformationlabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        personalInformationlabel1.setText("Personal Information");

        securityQuestionLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        securityQuestionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        securityQuestionLabel.setText("Security Question :");

        securityQuestion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        securityQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your pet's name ?", "What is your favorite object ?", "What is your primary school teacher's surname ?", "Where do you want to live ?", "Or enter random sentence (recommended)." }));

        securityAnswerLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        securityAnswerLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        securityAnswerLabel.setText("Answer :");

        securityAnswerText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        applyButton.setBackground(new java.awt.Color(204, 204, 255));
        applyButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        applyButton.setText("Apply");
        applyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        applyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                applyButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                applyButtonMouseExited(evt);
            }
        });
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        previousIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/previousIcon.png"))); // NOI18N
        previousIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        previousIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout applyPagePanelLayout = new javax.swing.GroupLayout(applyPagePanel);
        applyPagePanel.setLayout(applyPagePanelLayout);
        applyPagePanelLayout.setHorizontalGroup(
            applyPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, applyPagePanelLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(applyPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(applyPagePanelLayout.createSequentialGroup()
                        .addComponent(phoneNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(phoneNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(applyPagePanelLayout.createSequentialGroup()
                        .addComponent(customerNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(customerNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
            .addGroup(applyPagePanelLayout.createSequentialGroup()
                .addGroup(applyPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(applyPagePanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(securityAnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(applyPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(securityAnswerText, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(applyPagePanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(securityQuestionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(securityQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(applyPagePanelLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(personalInformationlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(applyPagePanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(adSoyadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(adSoyadText, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(previousIcon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(applyPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(applyPagePanelLayout.createSequentialGroup()
                    .addGap(115, 115, 115)
                    .addComponent(personalInformationlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(285, Short.MAX_VALUE)))
        );

        applyPagePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {adSoyadText, customerNoText, phoneNoText, securityQuestion});

        applyPagePanelLayout.setVerticalGroup(
            applyPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applyPagePanelLayout.createSequentialGroup()
                .addComponent(previousIcon)
                .addGap(72, 72, 72)
                .addGroup(applyPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adSoyadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adSoyadText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(applyPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(applyPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(personalInformationlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(applyPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(securityQuestionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(securityQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(applyPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(securityAnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(securityAnswerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(applyPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(applyPagePanelLayout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(personalInformationlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(309, Short.MAX_VALUE)))
        );

        applyPagePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {adSoyadLabel, adSoyadText, customerNoText, phoneNoText});

        applyPagePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {securityAnswerText, securityQuestion, securityQuestionLabel});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(applyPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(applyPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adSoyadTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adSoyadTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adSoyadTextActionPerformed

    private void applyButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applyButtonMouseEntered
        ButtonSettings.setBgFg(applyButton, Color.black, Color.white);
    }//GEN-LAST:event_applyButtonMouseEntered

    private void applyButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applyButtonMouseExited
        ButtonSettings.setOriginalBgFg(applyButton);
    }//GEN-LAST:event_applyButtonMouseExited

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        if (this.validInformation()) {
            this.makesTheApply();
        } else {
            Dialogs.notEmptyMessage(this);
        }

    }//GEN-LAST:event_applyButtonActionPerformed

    private void makesTheApply() {

        this.getUserApplyObject().setNameSurname(this.adSoyadText.getText().trim());
        this.getUserApplyObject().setCustomerNo(this.customerNoText.getText());
        this.getUserApplyObject().setPhoneNo(this.phoneNoText.getText());

        this.getUserApplyObject().setSecurityQuestion(String.valueOf(this.securityQuestion.getSelectedItem()));
        this.getUserApplyObject().setSecurityAnswer(this.securityAnswerText.getText().trim());

        this.getUserApplyObject().setMusteriNo(this.randomMusteriNo());
        this.getUserApplyObject().setPassword(this.randomPassword());

        if (this.getUserApplyObject().applyApproval()) {
            Dialogs.showSpecialMessage(this, "Your apply has been accepted...\n"
                    + "Musteri No:" + this.getUserApplyObject().getMusteriNo()
                    + "\nŞifreniz:" +this.getUserApplyObject().getPassword());
            ActionSettings.setVisible(this, new LoginPage());
        } else {
            Dialogs.showSpecialMessage(this, "Your apply has not been accepted. \n"
                    + "Please check your information!!!");

        }

    }

    private String randomMusteriNo() {
        String musteriNo;
        do{
        musteriNo = String.valueOf(1000000 + (int) Math.random() * 9000000);
        }while(this.getUserApplyObject().onlyOneMusteriNo());
        return musteriNo;
    }

    private String randomPassword() {
        String password;
        password = String.valueOf(1000 + (int) Math.random() * 9000);
        return password;
    }

    private void previousIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousIconMouseClicked
        ActionSettings.setVisible(this, new LoginPage());
    }//GEN-LAST:event_previousIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplyPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adSoyadLabel;
    private javax.swing.JLabel adSoyadLabel2;
    private javax.swing.JTextField adSoyadText;
    private javax.swing.JTextField adSoyadText2;
    private javax.swing.JButton applyButton;
    private javax.swing.JPanel applyPagePanel;
    private javax.swing.JLabel customerNoLabel;
    private javax.swing.JTextField customerNoText;
    private javax.swing.JLabel personalInformationlabel;
    private javax.swing.JLabel personalInformationlabel1;
    private javax.swing.JLabel phoneNoLabel;
    private javax.swing.JTextField phoneNoText;
    private javax.swing.JLabel previousIcon;
    private javax.swing.JLabel securityAnswerLabel;
    private javax.swing.JTextField securityAnswerText;
    private javax.swing.JComboBox<String> securityQuestion;
    private javax.swing.JLabel securityQuestionLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void getEdits() {
        this.setLocationRelativeTo(null);
        applyPagePanel.setFocusable(true);
        TextSettings.setOnlyAlphabetic(adSoyadText);
        TextSettings.setOnlyNumber(customerNoText);
        TextSettings.setOnlyNumber(phoneNoText);
        TextSettings.setMaxLimit(customerNoText, 11);
        TextSettings.setMaxLimit(phoneNoText, 11);
    }

    public UserApply getUserApplyObject() {
        if (this.userApplyObject == null) {
            userApplyObject = new UserApply();
        }
        return userApplyObject;
    }

    @Override
    public boolean validInformation() {
        return TextSettings.textFildFilling(applyPagePanel);
    }

    @Override
    public AccountInformation getAccountInformation() {
        return AccountInformation.getInstance();
    }

}
