/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.settings.ActionSettings;
import gui.settings.IRegulyator;
import gui.settings.TextSettings;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class DepositMoneyPage extends javax.swing.JFrame implements IRegulyator{

    private int depositMoneyQuantity = 0;
    
    /**
     * Creates new form DepositMoneyPage
     */
    public DepositMoneyPage() {
        initComponents();
        getEdits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        depositmoneyPagePanel = new javax.swing.JPanel();
        userNameSurnameLabel = new javax.swing.JLabel();
        limitWarningLabel = new javax.swing.JLabel();
        depositmoneyQuantity = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        totalBalance = new javax.swing.JLabel();
        depositmoneyQuantityText = new javax.swing.JTextField();
        depositMoneyButton = new javax.swing.JButton();
        previousIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        depositmoneyPagePanel.setBackground(new java.awt.Color(204, 204, 255));

        userNameSurnameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userNameSurnameLabel.setForeground(new java.awt.Color(255, 102, 102));
        userNameSurnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userNameSurnameLabel.setText("[KULLANICI ADI SOYADI]");

        limitWarningLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        limitWarningLabel.setText("You can deposit 50000$ and below at once.");

        depositmoneyQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        depositmoneyQuantity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        depositmoneyQuantity.setText("How much will you deposit :");

        balanceLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        balanceLabel.setText("[Balance]");

        totalBalance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalBalance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalBalance.setText(" Your total balance :");

        depositmoneyQuantityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositmoneyQuantityTextActionPerformed(evt);
            }
        });
        depositmoneyQuantityText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                depositmoneyQuantityTextKeyReleased(evt);
            }
        });

        depositMoneyButton.setText("Deposit Money");
        depositMoneyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        depositMoneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositMoneyButtonActionPerformed(evt);
            }
        });

        previousIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/previousIcon.png"))); // NOI18N
        previousIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        previousIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout depositmoneyPagePanelLayout = new javax.swing.GroupLayout(depositmoneyPagePanel);
        depositmoneyPagePanel.setLayout(depositmoneyPagePanelLayout);
        depositmoneyPagePanelLayout.setHorizontalGroup(
            depositmoneyPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositmoneyPagePanelLayout.createSequentialGroup()
                .addGroup(depositmoneyPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, depositmoneyPagePanelLayout.createSequentialGroup()
                        .addContainerGap(85, Short.MAX_VALUE)
                        .addComponent(userNameSurnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(depositmoneyPagePanelLayout.createSequentialGroup()
                        .addGroup(depositmoneyPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(depositmoneyPagePanelLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(limitWarningLabel))
                            .addComponent(previousIcon)
                            .addGroup(depositmoneyPagePanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(totalBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(balanceLabel))
                            .addGroup(depositmoneyPagePanelLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(depositmoneyQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(depositmoneyPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(depositMoneyButton)
                                    .addComponent(depositmoneyQuantityText, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        depositmoneyPagePanelLayout.setVerticalGroup(
            depositmoneyPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositmoneyPagePanelLayout.createSequentialGroup()
                .addComponent(previousIcon)
                .addGap(27, 27, 27)
                .addComponent(userNameSurnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(limitWarningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(depositmoneyPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(depositmoneyPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositmoneyQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depositmoneyQuantityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(depositMoneyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(depositmoneyPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(depositmoneyPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depositmoneyQuantityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositmoneyQuantityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depositmoneyQuantityTextActionPerformed

    private void depositmoneyQuantityTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_depositmoneyQuantityTextKeyReleased
        this.depositMoneyQuantity = TextSettings.checkTheTextKeyReleased(depositmoneyQuantityText, 50000);
    }//GEN-LAST:event_depositmoneyQuantityTextKeyReleased

    private void depositMoneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositMoneyButtonActionPerformed
        JOptionPane.showMessageDialog(this, "SUCCESSFUL.\n"
            + "Deposit Quantity :" + this.depositMoneyQuantity + " $");
        ActionSettings.setVisible(this, new AccountPage());
    }//GEN-LAST:event_depositMoneyButtonActionPerformed

    private void previousIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousIconMouseClicked
        ActionSettings.setVisible(this, new AccountPage());
    }//GEN-LAST:event_previousIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepositMoneyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepositMoneyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepositMoneyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepositMoneyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepositMoneyPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JButton depositMoneyButton;
    private javax.swing.JPanel depositmoneyPagePanel;
    private javax.swing.JLabel depositmoneyQuantity;
    private javax.swing.JTextField depositmoneyQuantityText;
    private javax.swing.JLabel limitWarningLabel;
    private javax.swing.JLabel previousIcon;
    private javax.swing.JLabel totalBalance;
    private javax.swing.JLabel userNameSurnameLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void getEdits() {
    this.setLocationRelativeTo(null);
    depositmoneyPagePanel.setFocusable(true);
    TextSettings.setOnlyNumber(depositmoneyQuantityText);
    TextSettings.setMaxLimit(depositmoneyQuantityText, 5);
        
    }
}
