package gui;

import database.DbConnection;
import database.InformationController;
import database.transactions.AccountInformation;
import database.transactions.UserLogin;
import gui.settings.ActionSettings;
import gui.settings.ButtonSettings;
import gui.settings.Dialogs;
import gui.settings.IRegulyator;
import gui.settings.TextSettings;
import java.awt.Color;


public final class LoginPage extends javax.swing.JFrame implements IRegulyator, InformationController{

    private UserLogin userLoginObject = null;
    
    public final String ID_TEXT_ORIGINAL = "T.C. No / Customer No";
    public final String PASSWORD_TEXT_ORIGINAL = "********";
    
    public LoginPage() {
        initComponents();
        getEdits();
        new DbConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPage = new javax.swing.JPanel();
        welcomeMesssageLabel = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        PasswordText = new javax.swing.JPasswordField();
        applyBtn = new javax.swing.JButton();
        answerLabel = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sweet Bank Login Page");

        loginPage.setBackground(new java.awt.Color(204, 255, 204));
        loginPage.setForeground(new java.awt.Color(102, 102, 102));
        loginPage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        welcomeMesssageLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        welcomeMesssageLabel.setForeground(new java.awt.Color(255, 0, 0));
        welcomeMesssageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeMesssageLabel.setText("     WELCOME  TO THE SWEET BANK");

        idText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idText.setForeground(new java.awt.Color(102, 102, 102));
        idText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idTextFocusLost(evt);
            }
        });
        idText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextActionPerformed(evt);
            }
        });

        PasswordText.setForeground(new java.awt.Color(102, 102, 102));
        PasswordText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordTextFocusLost(evt);
            }
        });
        PasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextActionPerformed(evt);
            }
        });

        applyBtn.setBackground(new java.awt.Color(153, 255, 153));
        applyBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        applyBtn.setText("Apply");
        applyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                applyBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                applyBtnMouseExited(evt);
            }
        });
        applyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyBtnActionPerformed(evt);
            }
        });

        answerLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        answerLabel.setText("You are not yot our customer  ?");

        btn1.setBackground(new java.awt.Color(255, 204, 204));
        btn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn1.setText("Login");
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn1MouseExited(evt);
            }
        });
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Forgot your password?");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginPageLayout = new javax.swing.GroupLayout(loginPage);
        loginPage.setLayout(loginPageLayout);
        loginPageLayout.setHorizontalGroup(
            loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPageLayout.createSequentialGroup()
                .addGroup(loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPageLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(loginPageLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(btn1))
                    .addGroup(loginPageLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(welcomeMesssageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPageLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(answerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(applyBtn))
                    .addGroup(loginPageLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel1)))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        loginPageLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {PasswordText, idText});

        loginPageLayout.setVerticalGroup(
            loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPageLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(welcomeMesssageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(btn1)
                .addGap(57, 57, 57)
                .addGroup(loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answerLabel)
                    .addComponent(applyBtn))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        loginPageLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {PasswordText, idText});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextActionPerformed

    private void PasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextActionPerformed

    private void applyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyBtnActionPerformed
        ActionSettings.setVisible(this, new ApplyPage());
    }//GEN-LAST:event_applyBtnActionPerformed
/*
*button renglendirilmeleri  
*/
    private void btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseEntered
        ButtonSettings.setBgFg(btn1, Color.cyan, Color.blue);
    }//GEN-LAST:event_btn1MouseEntered

    private void btn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseExited
        ButtonSettings.setOriginalBgFg(btn1);
    }//GEN-LAST:event_btn1MouseExited

    private void applyBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applyBtnMouseEntered
        ButtonSettings.setBgFg(applyBtn, Color.magenta, Color.green);
    }//GEN-LAST:event_applyBtnMouseEntered

    private void applyBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applyBtnMouseExited
        ButtonSettings.setOriginalBgFg(applyBtn);
    }//GEN-LAST:event_applyBtnMouseExited
/*
* text odaklanmalari    
*/
    private void idTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTextFocusGained
        TextSettings.checkTheTextFocusGained(idText, ID_TEXT_ORIGINAL);
    }//GEN-LAST:event_idTextFocusGained

    private void idTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTextFocusLost
        TextSettings.checkTheTextFocusLost(idText);
    }//GEN-LAST:event_idTextFocusLost

    private void PasswordTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordTextFocusGained
        TextSettings.checkTheTextFocusGained(PasswordText, PASSWORD_TEXT_ORIGINAL);
    }//GEN-LAST:event_PasswordTextFocusGained

    private void PasswordTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordTextFocusLost
        TextSettings.checkTheTextFocusLost(PasswordText);
    }//GEN-LAST:event_PasswordTextFocusLost
/*
* button action    
*/
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if(this.validInformation()){
            String customerId = this.idText.getText().trim();
            String password = String.valueOf(this.PasswordText.getPassword());
            this.login(customerId, password);
        } else {
            Dialogs.notEmptyMessage(this);
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void login(String customerId, String password){
        
        this.getUserLoginObject().setCustomerId(customerId);
        this.getUserLoginObject().setPassword(password);
        
        if(getUserLoginObject().loginInformationIsTrue()){
            ActionSettings.setVisible(this, new AccountPage());
        } else {
            Dialogs.showSpecialMessage(this, "Login information is not true!\n"
                    + "Please check your information!!");
        }
    }
    
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        PasswordResetPage prp = new PasswordResetPage();
        ActionSettings.setVisible(this, prp);
        prp.getOldPasswordText().setEnabled(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordText;
    private javax.swing.JLabel answerLabel;
    private javax.swing.JButton applyBtn;
    private javax.swing.JButton btn1;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel loginPage;
    private javax.swing.JLabel welcomeMesssageLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void getEdits() {
        this.setLocationRelativeTo(null);
        loginPage.setFocusable(true);
        idText.setText(ID_TEXT_ORIGINAL);
        PasswordText.setText(PASSWORD_TEXT_ORIGINAL);
        TextSettings.setOnlyNumber(idText);
    }

    @Override
    public boolean validInformation() {
        return !(this.idText.getText().equals(this.ID_TEXT_ORIGINAL)
                || String.valueOf(this.PasswordText.getPassword()).equals(this.PASSWORD_TEXT_ORIGINAL));
    }

    @Override
    public AccountInformation getAccountInformation() {
        return AccountInformation.getInstance();
    }

    public UserLogin getUserLoginObject() {
        if(this.userLoginObject == null){
            userLoginObject = new UserLogin();
        }
        return userLoginObject;
    }
    
    
}
