/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.settings.ActionSettings;
import gui.settings.ButtonSettings;
import gui.settings.IRegulyator;
import gui.settings.TextSettings;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author user
 */
public class PasswordResetPage extends javax.swing.JFrame implements IRegulyator {

    /**
     * Creates new form PasswordResetPage
     */
    public PasswordResetPage() {
        initComponents();
        getEdits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordResetPanel = new javax.swing.JPanel();
        previousIcon = new javax.swing.JLabel();
        passwordResetLabel = new javax.swing.JLabel();
        customerNoLabel = new javax.swing.JLabel();
        customerNoText = new javax.swing.JTextField();
        phoneNoText = new javax.swing.JTextField();
        phoneNoLabel = new javax.swing.JLabel();
        securityQuestionAnswerText = new javax.swing.JTextField();
        securityQuestionAnswerlabel = new javax.swing.JLabel();
        oldPasswordLabel = new javax.swing.JLabel();
        newPasswordlabel = new javax.swing.JLabel();
        newPasswordRepeatLabel = new javax.swing.JLabel();
        oldPasswordText = new javax.swing.JPasswordField();
        newPasswordText = new javax.swing.JPasswordField();
        newPasswordRepeatText = new javax.swing.JPasswordField();
        passwordUpdatedButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        passwordResetPanel.setBackground(new java.awt.Color(102, 255, 204));

        previousIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/previousIcon.png"))); // NOI18N
        previousIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        previousIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousIconMouseClicked(evt);
            }
        });

        passwordResetLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        passwordResetLabel.setForeground(new java.awt.Color(255, 0, 51));
        passwordResetLabel.setText("Password Reset");

        customerNoLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        customerNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        customerNoLabel.setText("Customer NO :");

        customerNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNoTextActionPerformed(evt);
            }
        });

        phoneNoLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phoneNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        phoneNoLabel.setText("Phone NO :");

        securityQuestionAnswerlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        securityQuestionAnswerlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        securityQuestionAnswerlabel.setText("Security Question Answer :");

        oldPasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        oldPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        oldPasswordLabel.setText("Old Password :");

        newPasswordlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newPasswordlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        newPasswordlabel.setText("New Password :");

        newPasswordRepeatLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newPasswordRepeatLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        newPasswordRepeatLabel.setText("New Password Repeat :");

        passwordUpdatedButton.setBackground(new java.awt.Color(255, 255, 102));
        passwordUpdatedButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordUpdatedButton.setText("Password Updated");
        passwordUpdatedButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passwordUpdatedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passwordUpdatedButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passwordUpdatedButtonMouseExited(evt);
            }
        });
        passwordUpdatedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordUpdatedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout passwordResetPanelLayout = new javax.swing.GroupLayout(passwordResetPanel);
        passwordResetPanel.setLayout(passwordResetPanelLayout);
        passwordResetPanelLayout.setHorizontalGroup(
            passwordResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordResetPanelLayout.createSequentialGroup()
                .addComponent(previousIcon)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(passwordResetPanelLayout.createSequentialGroup()
                .addGroup(passwordResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(passwordResetPanelLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(passwordResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(passwordResetPanelLayout.createSequentialGroup()
                                .addComponent(phoneNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(phoneNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(passwordResetPanelLayout.createSequentialGroup()
                                .addComponent(customerNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(customerNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(passwordResetPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(securityQuestionAnswerlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(securityQuestionAnswerText, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(passwordResetPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(passwordResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newPasswordRepeatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newPasswordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oldPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(passwordResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oldPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newPasswordRepeatText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(passwordResetPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(passwordResetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(passwordResetPanelLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(passwordUpdatedButton)))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        passwordResetPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {newPasswordRepeatText, newPasswordText, oldPasswordText, securityQuestionAnswerText});

        passwordResetPanelLayout.setVerticalGroup(
            passwordResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordResetPanelLayout.createSequentialGroup()
                .addComponent(previousIcon)
                .addGap(4, 4, 4)
                .addComponent(passwordResetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(passwordResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(passwordResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(passwordResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(securityQuestionAnswerlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(securityQuestionAnswerText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(passwordResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oldPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(passwordResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPasswordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(passwordResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPasswordRepeatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPasswordRepeatText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(passwordUpdatedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        passwordResetPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {newPasswordRepeatText, newPasswordText, oldPasswordText, securityQuestionAnswerText});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passwordResetPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passwordResetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean isEnabledOldPasswordText() {
        return this.getOldPasswordText().isEnabled();
    }

    private void previousIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousIconMouseClicked
        if (isEnabledOldPasswordText()) {
            ActionSettings.setVisible(this, new SettingsPage());
        } else {
            ActionSettings.setVisible(this, new LoginPage());
        }

    }//GEN-LAST:event_previousIconMouseClicked

    private void customerNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNoTextActionPerformed
        
    }//GEN-LAST:event_customerNoTextActionPerformed

    private void passwordUpdatedButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordUpdatedButtonMouseEntered
        ButtonSettings.setBgFg(passwordUpdatedButton, Color.cyan, Color.red);
    }//GEN-LAST:event_passwordUpdatedButtonMouseEntered

    private void passwordUpdatedButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordUpdatedButtonMouseExited
        ButtonSettings.setOriginalBgFg(passwordUpdatedButton);
    }//GEN-LAST:event_passwordUpdatedButtonMouseExited

    private void passwordUpdatedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordUpdatedButtonActionPerformed
        JOptionPane.showMessageDialog(this, "Password updated successfully");
        if (isEnabledOldPasswordText()) {
            ActionSettings.setVisible(this, new AccountPage());
        } else {
            ActionSettings.setVisible(this, new LoginPage());
        }
    }//GEN-LAST:event_passwordUpdatedButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordResetPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordResetPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordResetPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordResetPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasswordResetPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customerNoLabel;
    private javax.swing.JTextField customerNoText;
    private javax.swing.JLabel newPasswordRepeatLabel;
    private javax.swing.JPasswordField newPasswordRepeatText;
    private javax.swing.JPasswordField newPasswordText;
    private javax.swing.JLabel newPasswordlabel;
    private javax.swing.JLabel oldPasswordLabel;
    private javax.swing.JPasswordField oldPasswordText;
    private javax.swing.JLabel passwordResetLabel;
    private javax.swing.JPanel passwordResetPanel;
    private javax.swing.JButton passwordUpdatedButton;
    private javax.swing.JLabel phoneNoLabel;
    private javax.swing.JTextField phoneNoText;
    private javax.swing.JLabel previousIcon;
    private javax.swing.JTextField securityQuestionAnswerText;
    private javax.swing.JLabel securityQuestionAnswerlabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void getEdits() {
        this.setLocationRelativeTo(null);
        TextSettings.setOnlyNumber(customerNoText);
        TextSettings.setMaxLimit(customerNoText, 11);
        TextSettings.setOnlyNumber(phoneNoText);
        TextSettings.setMaxLimit(phoneNoText, 11);
    }

    public JPasswordField getOldPasswordText() {
        return oldPasswordText;
    }
}
