/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.settings.ActionSettings;
import gui.settings.ButtonSettings;
import gui.settings.IRegulyator;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class PaymentsPage extends javax.swing.JFrame implements IRegulyator{

    /**
     * Creates new form PaymentsPage
     */
    public PaymentsPage() {
        initComponents();
        getEdits();
    }
    
    private void setBgFg(Component c){
        ButtonSettings.setBgFg((JButton)c, Color.black, Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentsPagePanel = new javax.swing.JPanel();
        userNameSurnameLabel = new javax.swing.JLabel();
        previousIcon = new javax.swing.JLabel();
        messageElek = new javax.swing.JLabel();
        electricDebt = new javax.swing.JLabel();
        electricPayButton = new javax.swing.JButton();
        messageWater = new javax.swing.JLabel();
        waterDebt = new javax.swing.JLabel();
        waterPayButton = new javax.swing.JButton();
        messageInt = new javax.swing.JLabel();
        intDebt = new javax.swing.JLabel();
        gasPayButton = new javax.swing.JButton();
        messageGas = new javax.swing.JLabel();
        gasDebt = new javax.swing.JLabel();
        intPayButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paymentsPagePanel.setBackground(new java.awt.Color(204, 255, 204));

        userNameSurnameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userNameSurnameLabel.setForeground(new java.awt.Color(255, 102, 102));
        userNameSurnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userNameSurnameLabel.setText("[KULLANICI ADI SOYADI]");

        previousIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/previousIcon.png"))); // NOI18N
        previousIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        previousIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousIconMouseClicked(evt);
            }
        });

        messageElek.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        messageElek.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        messageElek.setText("Your total electricity bill debt :");

        electricDebt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        electricDebt.setForeground(new java.awt.Color(255, 51, 51));
        electricDebt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        electricDebt.setText("[ELEKT BORC]");

        electricPayButton.setBackground(new java.awt.Color(255, 204, 204));
        electricPayButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        electricPayButton.setText("PAY");
        electricPayButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        electricPayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                electricPayButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                electricPayButtonMouseExited(evt);
            }
        });
        electricPayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electricPayButtonActionPerformed(evt);
            }
        });

        messageWater.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        messageWater.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        messageWater.setText("Your total water bill debt :");

        waterDebt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        waterDebt.setForeground(new java.awt.Color(255, 51, 51));
        waterDebt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        waterDebt.setText("[SU BORC]");

        waterPayButton.setBackground(new java.awt.Color(255, 204, 204));
        waterPayButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        waterPayButton.setText("PAY");
        waterPayButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        waterPayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                waterPayButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                waterPayButtonMouseExited(evt);
            }
        });
        waterPayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterPayButtonActionPerformed(evt);
            }
        });

        messageInt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        messageInt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        messageInt.setText("Your total internet bill debt :");

        intDebt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        intDebt.setForeground(new java.awt.Color(255, 51, 51));
        intDebt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        intDebt.setText("[INT BORC]");

        gasPayButton.setBackground(new java.awt.Color(255, 204, 204));
        gasPayButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gasPayButton.setText("PAY");
        gasPayButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gasPayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gasPayButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gasPayButtonMouseExited(evt);
            }
        });
        gasPayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gasPayButtonActionPerformed(evt);
            }
        });

        messageGas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        messageGas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        messageGas.setText("Your total gas bill debt :");

        gasDebt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gasDebt.setForeground(new java.awt.Color(255, 51, 51));
        gasDebt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gasDebt.setText("[GAS BORC]");

        intPayButton.setBackground(new java.awt.Color(255, 204, 204));
        intPayButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        intPayButton.setText("PAY");
        intPayButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        intPayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                intPayButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                intPayButtonMouseExited(evt);
            }
        });
        intPayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intPayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paymentsPagePanelLayout = new javax.swing.GroupLayout(paymentsPagePanel);
        paymentsPagePanel.setLayout(paymentsPagePanelLayout);
        paymentsPagePanelLayout.setHorizontalGroup(
            paymentsPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentsPagePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(userNameSurnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addGroup(paymentsPagePanelLayout.createSequentialGroup()
                .addGroup(paymentsPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(previousIcon)
                    .addGroup(paymentsPagePanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(paymentsPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paymentsPagePanelLayout.createSequentialGroup()
                                .addComponent(messageElek, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(electricDebt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(electricPayButton))
                            .addGroup(paymentsPagePanelLayout.createSequentialGroup()
                                .addComponent(messageGas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(gasDebt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(gasPayButton))
                            .addGroup(paymentsPagePanelLayout.createSequentialGroup()
                                .addComponent(messageWater, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(waterDebt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(waterPayButton))
                            .addGroup(paymentsPagePanelLayout.createSequentialGroup()
                                .addComponent(messageInt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(intDebt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(intPayButton)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        paymentsPagePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {electricDebt, gasDebt, intDebt, waterDebt});

        paymentsPagePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {electricPayButton, gasPayButton, intPayButton, waterPayButton});

        paymentsPagePanelLayout.setVerticalGroup(
            paymentsPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentsPagePanelLayout.createSequentialGroup()
                .addComponent(previousIcon)
                .addGap(18, 18, 18)
                .addComponent(userNameSurnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(paymentsPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageElek, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(electricDebt)
                    .addComponent(electricPayButton))
                .addGap(18, 18, 18)
                .addGroup(paymentsPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageWater, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waterDebt)
                    .addComponent(waterPayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paymentsPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageGas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gasDebt)
                    .addComponent(gasPayButton))
                .addGap(18, 18, 18)
                .addGroup(paymentsPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageInt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intDebt)
                    .addComponent(intPayButton))
                .addGap(0, 170, Short.MAX_VALUE))
        );

        paymentsPagePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {electricDebt, gasDebt, intDebt, messageElek, waterDebt});

        paymentsPagePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {electricPayButton, gasPayButton, intPayButton, waterPayButton});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paymentsPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paymentsPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void previousIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousIconMouseClicked
        ActionSettings.setVisible(this, new AccountPage());
    }//GEN-LAST:event_previousIconMouseClicked

    //
    
    private void electricPayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electricPayButtonActionPerformed
       JOptionPane.showMessageDialog(this, "Electricity payment Successful.");
       ActionSettings.setVisible(this, new AccountPage());
    }//GEN-LAST:event_electricPayButtonActionPerformed

    private void waterPayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterPayButtonActionPerformed
       JOptionPane.showMessageDialog(this, "Water payment Successful.");
       ActionSettings.setVisible(this, new AccountPage());
    }//GEN-LAST:event_waterPayButtonActionPerformed

    private void gasPayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gasPayButtonActionPerformed
       JOptionPane.showMessageDialog(this, "Gas payment Successful.");
       ActionSettings.setVisible(this, new AccountPage());
    }//GEN-LAST:event_gasPayButtonActionPerformed

    private void intPayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intPayButtonActionPerformed
       JOptionPane.showMessageDialog(this, "Internet payment Successful.");
       ActionSettings.setVisible(this, new AccountPage());
    }//GEN-LAST:event_intPayButtonActionPerformed

    //
    
    private void electricPayButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_electricPayButtonMouseEntered
       this.setBgFg(evt.getComponent());
    }//GEN-LAST:event_electricPayButtonMouseEntered

    private void electricPayButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_electricPayButtonMouseExited
       ButtonSettings.setOriginalBgFg((JButton) evt.getComponent());
    }//GEN-LAST:event_electricPayButtonMouseExited

    private void waterPayButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_waterPayButtonMouseEntered
       this.setBgFg(evt.getComponent());
    }//GEN-LAST:event_waterPayButtonMouseEntered

    private void waterPayButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_waterPayButtonMouseExited
       ButtonSettings.setOriginalBgFg((JButton) evt.getComponent());
    }//GEN-LAST:event_waterPayButtonMouseExited

    private void gasPayButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gasPayButtonMouseEntered
       this.setBgFg(evt.getComponent());
    }//GEN-LAST:event_gasPayButtonMouseEntered

    private void gasPayButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gasPayButtonMouseExited
       ButtonSettings.setOriginalBgFg((JButton) evt.getComponent());
    }//GEN-LAST:event_gasPayButtonMouseExited

    private void intPayButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_intPayButtonMouseEntered
       this.setBgFg(evt.getComponent());
    }//GEN-LAST:event_intPayButtonMouseEntered

    private void intPayButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_intPayButtonMouseExited
       ButtonSettings.setOriginalBgFg((JButton) evt.getComponent());
    }//GEN-LAST:event_intPayButtonMouseExited

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel electricDebt;
    private javax.swing.JButton electricPayButton;
    private javax.swing.JLabel gasDebt;
    private javax.swing.JButton gasPayButton;
    private javax.swing.JLabel intDebt;
    private javax.swing.JButton intPayButton;
    private javax.swing.JLabel messageElek;
    private javax.swing.JLabel messageGas;
    private javax.swing.JLabel messageInt;
    private javax.swing.JLabel messageWater;
    private javax.swing.JPanel paymentsPagePanel;
    private javax.swing.JLabel previousIcon;
    private javax.swing.JLabel userNameSurnameLabel;
    private javax.swing.JLabel waterDebt;
    private javax.swing.JButton waterPayButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void getEdits() {
    this.setLocationRelativeTo(null);
    paymentsPagePanel.setFocusable(true);
    }
}
