/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.settings.ActionSettings;
import gui.settings.IRegulyator;
import gui.settings.IconSettings;
import gui.settings.TextSettings;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class SettingsPage extends javax.swing.JFrame implements IRegulyator{

    /**
     * Creates new form SettingsPage
     */
    public SettingsPage() {
       initComponents();
       getEdits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingsPagePanel = new javax.swing.JPanel();
        userNameSurnameLabel = new javax.swing.JLabel();
        previousIcon = new javax.swing.JLabel();
        messagePhoneNoLabel = new javax.swing.JLabel();
        phoneNoText = new javax.swing.JTextField();
        phoneNoChangeIcon = new javax.swing.JLabel();
        messagePasswordLabel = new javax.swing.JLabel();
        passwordText = new javax.swing.JTextField();
        passwordChangeIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        settingsPagePanel.setBackground(new java.awt.Color(255, 204, 204));

        userNameSurnameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userNameSurnameLabel.setForeground(new java.awt.Color(255, 102, 102));
        userNameSurnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userNameSurnameLabel.setText("[KULLANICI ADI SOYADI]");

        previousIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/previousIcon.png"))); // NOI18N
        previousIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        previousIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousIconMouseClicked(evt);
            }
        });

        messagePhoneNoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        messagePhoneNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        messagePhoneNoLabel.setText("Phone Number :");

        phoneNoText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phoneNoText.setEnabled(false);
        phoneNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNoTextActionPerformed(evt);
            }
        });

        phoneNoChangeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/updatePhoneNoIcon.png"))); // NOI18N
        phoneNoChangeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        phoneNoChangeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoneNoChangeIconMouseClicked(evt);
            }
        });

        messagePasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        messagePasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        messagePasswordLabel.setText("Password :");

        passwordText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordText.setText("********");
        passwordText.setEnabled(false);
        passwordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextActionPerformed(evt);
            }
        });

        passwordChangeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/updatePhoneNoIcon.png"))); // NOI18N
        passwordChangeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passwordChangeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordChangeIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout settingsPagePanelLayout = new javax.swing.GroupLayout(settingsPagePanel);
        settingsPagePanel.setLayout(settingsPagePanelLayout);
        settingsPagePanelLayout.setHorizontalGroup(
            settingsPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsPagePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(userNameSurnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(settingsPagePanelLayout.createSequentialGroup()
                .addGroup(settingsPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(previousIcon)
                    .addGroup(settingsPagePanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(settingsPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(messagePasswordLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(messagePhoneNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(settingsPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(settingsPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordChangeIcon)
                            .addComponent(phoneNoChangeIcon))))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        settingsPagePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {messagePhoneNoLabel, passwordText, phoneNoText});

        settingsPagePanelLayout.setVerticalGroup(
            settingsPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPagePanelLayout.createSequentialGroup()
                .addComponent(previousIcon)
                .addGap(18, 18, 18)
                .addComponent(userNameSurnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(settingsPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneNoChangeIcon)
                    .addGroup(settingsPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(messagePhoneNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phoneNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(settingsPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordChangeIcon)
                    .addGroup(settingsPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(messagePasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 210, Short.MAX_VALUE))
        );

        settingsPagePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {messagePhoneNoLabel, passwordText, phoneNoText});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(settingsPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(settingsPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void previousIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousIconMouseClicked
        ActionSettings.setVisible(this, new AccountPage());
    }//GEN-LAST:event_previousIconMouseClicked

    private void phoneNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNoTextActionPerformed

    private void passwordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextActionPerformed

    private int clickCounter = 0;
    
    private void phoneNoChangeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneNoChangeIconMouseClicked
        if(this.clickCounter == 0){ //daha evvel tiklanmamissa!
        phoneNoText.setEnabled(true);
        IconSettings.changeIcon(phoneNoChangeIcon, "updatePhoneNoIcon2");
        clickCounter++;
        }else { //daha evvel tiklanmissa!
            phoneNoText.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Phone number updated");
            IconSettings.setOriginalIcon(phoneNoChangeIcon);
            clickCounter = 0;
        }
    }//GEN-LAST:event_phoneNoChangeIconMouseClicked

    private void passwordChangeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordChangeIconMouseClicked
        ActionSettings.setVisible(this, new PasswordResetPage());
    }//GEN-LAST:event_passwordChangeIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel messagePasswordLabel;
    private javax.swing.JLabel messagePhoneNoLabel;
    private javax.swing.JLabel passwordChangeIcon;
    private javax.swing.JTextField passwordText;
    private javax.swing.JLabel phoneNoChangeIcon;
    private javax.swing.JTextField phoneNoText;
    private javax.swing.JLabel previousIcon;
    private javax.swing.JPanel settingsPagePanel;
    private javax.swing.JLabel userNameSurnameLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void getEdits() {
    this.setLocationRelativeTo(null);
    settingsPagePanel.setFocusable(true);
    TextSettings.setOnlyNumber(phoneNoText);
    TextSettings.setMaxLimit(phoneNoText, 11);
    }
}
