/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.settings.ActionSettings;
import gui.settings.IRegulyator;
import gui.settings.TextSettings;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class TransferPage extends javax.swing.JFrame implements IRegulyator{

    private final String CUSTOMER_NO_TEXT_ORIGINAL = "Customer No";
    
    private int sendAmount = 0;
    
    /**
     * Creates new form TransfePage
     */
    public TransferPage() {
        initComponents();
        getEdits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transferPagePanel = new javax.swing.JPanel();
        userNameSurnameLabel6 = new javax.swing.JLabel();
        limitWarningLabel6 = new javax.swing.JLabel();
        amoundLabel = new javax.swing.JLabel();
        balanceLabel6 = new javax.swing.JLabel();
        totalBalance6 = new javax.swing.JLabel();
        amountText = new javax.swing.JTextField();
        transferButton = new javax.swing.JButton();
        previousIcon6 = new javax.swing.JLabel();
        transfereeLabel = new javax.swing.JLabel();
        transfereeText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        transferPagePanel.setBackground(new java.awt.Color(255, 204, 255));

        userNameSurnameLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userNameSurnameLabel6.setForeground(new java.awt.Color(255, 102, 102));
        userNameSurnameLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userNameSurnameLabel6.setText("[KULLANICI ADI SOYADI]");

        limitWarningLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        limitWarningLabel6.setText("You can send 20000$ and below at once.");

        amoundLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        amoundLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        amoundLabel.setText("The amount you will send :");

        balanceLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        balanceLabel6.setText("[Balance]");

        totalBalance6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalBalance6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalBalance6.setText(" Your total balance :");

        amountText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        amountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTextActionPerformed(evt);
            }
        });
        amountText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amountTextKeyReleased(evt);
            }
        });

        transferButton.setText("Transfer Money");
        transferButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferButtonActionPerformed(evt);
            }
        });

        previousIcon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/previousIcon.png"))); // NOI18N
        previousIcon6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        previousIcon6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousIcon6MouseClicked(evt);
            }
        });

        transfereeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        transfereeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        transfereeLabel.setText("Transferee :");

        transfereeText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        transfereeText.setForeground(new java.awt.Color(102, 102, 102));
        transfereeText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                transfereeTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                transfereeTextFocusLost(evt);
            }
        });
        transfereeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfereeTextActionPerformed(evt);
            }
        });
        transfereeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                transfereeTextKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout transferPagePanelLayout = new javax.swing.GroupLayout(transferPagePanel);
        transferPagePanel.setLayout(transferPagePanelLayout);
        transferPagePanelLayout.setHorizontalGroup(
            transferPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transferPagePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(userNameSurnameLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(transferPagePanelLayout.createSequentialGroup()
                .addGroup(transferPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(previousIcon6)
                    .addGroup(transferPagePanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(totalBalance6, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(balanceLabel6))
                    .addGroup(transferPagePanelLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(limitWarningLabel6))
                    .addGroup(transferPagePanelLayout.createSequentialGroup()
                        .addGroup(transferPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(transferPagePanelLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(amoundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transferPagePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(transfereeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(transferPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transfereeText, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(transferPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transferPagePanelLayout.createSequentialGroup()
                                    .addComponent(transferButton)
                                    .addGap(25, 25, 25))))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        transferPagePanelLayout.setVerticalGroup(
            transferPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferPagePanelLayout.createSequentialGroup()
                .addComponent(previousIcon6)
                .addGap(20, 20, 20)
                .addComponent(userNameSurnameLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(limitWarningLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(transferPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalBalance6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balanceLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transferPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amoundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transferPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transfereeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transfereeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(transferButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transferPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transferPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTextActionPerformed

    private void amountTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountTextKeyReleased
        this.sendAmount = TextSettings.checkTheTextKeyReleased(amountText, 20000);
    }//GEN-LAST:event_amountTextKeyReleased

    private void transferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferButtonActionPerformed
        JOptionPane.showMessageDialog(this, "SUCCESSFUL.\n"
            + "Send Amount :" + this.sendAmount + " $");
        ActionSettings.setVisible(this, new AccountPage());
    }//GEN-LAST:event_transferButtonActionPerformed

    private void previousIcon6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousIcon6MouseClicked
        ActionSettings.setVisible(this, new AccountPage());
    }//GEN-LAST:event_previousIcon6MouseClicked

    private void transfereeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfereeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transfereeTextActionPerformed

    private void transfereeTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_transfereeTextKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_transfereeTextKeyReleased

    private void transfereeTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_transfereeTextFocusGained
        TextSettings.checkTheTextFocusGained(transfereeText, CUSTOMER_NO_TEXT_ORIGINAL);
    }//GEN-LAST:event_transfereeTextFocusGained

    private void transfereeTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_transfereeTextFocusLost
        TextSettings.checkTheTextFocusLost(transfereeText);
    }//GEN-LAST:event_transfereeTextFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransferPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransferPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransferPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransferPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransferPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amoundLabel;
    private javax.swing.JTextField amountText;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JLabel balanceLabel1;
    private javax.swing.JLabel balanceLabel2;
    private javax.swing.JLabel balanceLabel3;
    private javax.swing.JLabel balanceLabel4;
    private javax.swing.JLabel balanceLabel5;
    private javax.swing.JLabel balanceLabel6;
    private javax.swing.JLabel limitWarningLabel;
    private javax.swing.JLabel limitWarningLabel1;
    private javax.swing.JLabel limitWarningLabel2;
    private javax.swing.JLabel limitWarningLabel3;
    private javax.swing.JLabel limitWarningLabel4;
    private javax.swing.JLabel limitWarningLabel5;
    private javax.swing.JLabel limitWarningLabel6;
    private javax.swing.JLabel previousIcon;
    private javax.swing.JLabel previousIcon1;
    private javax.swing.JLabel previousIcon2;
    private javax.swing.JLabel previousIcon3;
    private javax.swing.JLabel previousIcon4;
    private javax.swing.JLabel previousIcon5;
    private javax.swing.JLabel previousIcon6;
    private javax.swing.JLabel totalBalance;
    private javax.swing.JLabel totalBalance1;
    private javax.swing.JLabel totalBalance2;
    private javax.swing.JLabel totalBalance3;
    private javax.swing.JLabel totalBalance4;
    private javax.swing.JLabel totalBalance5;
    private javax.swing.JLabel totalBalance6;
    private javax.swing.JButton transferButton;
    private javax.swing.JPanel transferPagePanel;
    private javax.swing.JLabel transfereeLabel;
    private javax.swing.JTextField transfereeText;
    private javax.swing.JLabel userNameSurnameLabel;
    private javax.swing.JLabel userNameSurnameLabel1;
    private javax.swing.JLabel userNameSurnameLabel2;
    private javax.swing.JLabel userNameSurnameLabel3;
    private javax.swing.JLabel userNameSurnameLabel4;
    private javax.swing.JLabel userNameSurnameLabel5;
    private javax.swing.JLabel userNameSurnameLabel6;
    private javax.swing.JButton withdrawMoneyButton;
    private javax.swing.JButton withdrawMoneyButton1;
    private javax.swing.JButton withdrawMoneyButton2;
    private javax.swing.JButton withdrawMoneyButton3;
    private javax.swing.JButton withdrawMoneyButton4;
    private javax.swing.JButton withdrawMoneyButton5;
    private javax.swing.JPanel withdrawmoneyPagePanel;
    private javax.swing.JPanel withdrawmoneyPagePanel1;
    private javax.swing.JPanel withdrawmoneyPagePanel2;
    private javax.swing.JPanel withdrawmoneyPagePanel3;
    private javax.swing.JPanel withdrawmoneyPagePanel4;
    private javax.swing.JPanel withdrawmoneyPagePanel5;
    private javax.swing.JLabel withdrawmoneyQuantity;
    private javax.swing.JLabel withdrawmoneyQuantity1;
    private javax.swing.JLabel withdrawmoneyQuantity2;
    private javax.swing.JLabel withdrawmoneyQuantity3;
    private javax.swing.JLabel withdrawmoneyQuantity4;
    private javax.swing.JLabel withdrawmoneyQuantity5;
    private javax.swing.JTextField withdrawmoneyQuantityText;
    private javax.swing.JTextField withdrawmoneyQuantityText1;
    private javax.swing.JTextField withdrawmoneyQuantityText2;
    private javax.swing.JTextField withdrawmoneyQuantityText3;
    private javax.swing.JTextField withdrawmoneyQuantityText4;
    private javax.swing.JTextField withdrawmoneyQuantityText5;
    // End of variables declaration//GEN-END:variables

    @Override
    public void getEdits() {
        this.setLocationRelativeTo(null);
        transferPagePanel.setFocusable(true);
        TextSettings.setOnlyNumber(amountText);
        TextSettings.setMaxLimit(amountText, 5);
        TextSettings.setOnlyNumber(transfereeText);
        transfereeText.setText(CUSTOMER_NO_TEXT_ORIGINAL);
    }
}
